apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: files
spec:
  type: pubsub.azure.servicebus.queues
  version: v1
  metadata:
  - name: connectionString
    value: 'Endpoint=sb://royerm.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=$AZURE_EVENTHUB_KEY'