apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: filestore
  namespace: unicorn
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6379
    - name: redisPassword
      value: ""
    - name: keyPrefix
      value: none
scopes:
  - unicorn-process
  - unicorn-publish